language: go
go:
  - "1.11"
services:
  - docker

install:
  - go get -u golang.org/x/lint/golint
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

before_script:
  - go vet ./...
  - go build ./...
  - go test -run xxxx ./...

script:
  - diff -u <(echo -n) <(gofmt -d -s `find . -type f -name '*.go' -not -path "./vendor/*"`)
  - diff -u <(echo -n) <(golint `go list ./... | grep -v /vendor/`)
  - go test -race -short -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications: 
  email: false 
