[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/RTradeLtd/cmd"
  version = "1.0.0"

[[constraint]]
  name = "github.com/RTradeLtd/config"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
